export type ExerciseEntry = {
    id: string;
    imageUrl: string;
    name: string;
    equipment: string;
    primaryMuscle: string;
    category: string;
    location: string[];
    difficulty: string[];
    sets: number;
    reps: string;
    restSeconds: number;
    /** Balanced effectiveness+popularity score (0–100), sourced from
     *  info/exercise-ranking.md. Primary selection sort key for the
     *  generator. */
    score: number;
    /** Explicit movement classification — replaces keyword-guessing
     *  in classifyCompoundness for the selection logic. */
    movement: 'compound' | 'isolation';
    /** True for the top compound / staple per muscle. Held stable
     *  across mesocycle blocks (the progression anchor); exempt from
     *  the variety deprioritization. */
    isPrimary: boolean;
};

export const EXERCISES: ExerciseEntry[] = [
    // PUSH - GYM
    { id: "push_001", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Bench_Press_-_Medium_Grip/0.jpg", name: "Barbell Bench Press", equipment: "barbell", primaryMuscle: "chest", category: "push", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 4, reps: "8-12", restSeconds: 90, score: 93, movement: "compound", isPrimary: true },
    { id: "push_002", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Incline_Bench_Press_-_Medium_Grip/0.jpg", name: "Incline Barbell Bench Press", equipment: "barbell", primaryMuscle: "chest", category: "push", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "8-12", restSeconds: 90, score: 92, movement: "compound", isPrimary: false },
    { id: "push_003", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bench_Press/0.jpg", name: "Dumbbell Bench Press", equipment: "dumbbell", primaryMuscle: "chest", category: "push", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "10-12", restSeconds: 90, score: 89, movement: "compound", isPrimary: false },
    { id: "push_004", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Press/0.jpg", name: "Incline Dumbbell Press", equipment: "dumbbell", primaryMuscle: "chest", category: "push", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "10-12", restSeconds: 90, score: 91, movement: "compound", isPrimary: false },
    { id: "push_005", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover/0.jpg", name: "Cable Fly", equipment: "cable", primaryMuscle: "chest", category: "push", location: ["gym"], difficulty: ["intermediate"], sets: 3, reps: "12-15", restSeconds: 60, score: 80, movement: "isolation", isPrimary: false },
    { id: "push_006", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Flyes/0.jpg", name: "Dumbbell Fly", equipment: "dumbbell", primaryMuscle: "chest", category: "push", location: ["gym"], difficulty: ["intermediate"], sets: 3, reps: "12-15", restSeconds: 60, score: 72, movement: "isolation", isPrimary: false },
    { id: "push_007", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Military_Press/0.jpg", name: "Overhead Press", equipment: "barbell", primaryMuscle: "shoulders", category: "push", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 4, reps: "8-12", restSeconds: 90, score: 90, movement: "compound", isPrimary: true },
    { id: "push_008", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Shoulder_Press/0.jpg", name: "Dumbbell Shoulder Press", equipment: "dumbbell", primaryMuscle: "shoulders", category: "push", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "10-12", restSeconds: 90, score: 84, movement: "compound", isPrimary: false },
    { id: "push_009", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Lateral_Raise/0.jpg", name: "Lateral Raise", equipment: "dumbbell", primaryMuscle: "shoulders", category: "push", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "12-15", restSeconds: 60, score: 90, movement: "isolation", isPrimary: false },
    { id: "push_010", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Dumbbell_Raise/0.jpg", name: "Front Raise", equipment: "dumbbell", primaryMuscle: "shoulders", category: "push", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "12-15", restSeconds: 60, score: 57, movement: "isolation", isPrimary: false },
    { id: "push_011", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Arnold_Dumbbell_Press/0.jpg", name: "Arnold Press", equipment: "dumbbell", primaryMuscle: "shoulders", category: "push", location: ["gym"], difficulty: ["intermediate"], sets: 3, reps: "10-12", restSeconds: 90, score: 76, movement: "compound", isPrimary: false },
    { id: "push_012", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Pushdown/0.jpg", name: "Tricep Pushdown", equipment: "cable", primaryMuscle: "triceps", category: "push", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "12-15", restSeconds: 60, score: 85, movement: "isolation", isPrimary: false },
    { id: "push_013", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Dumbbell_Tricep_Extension/0.jpg", name: "Overhead Tricep Extension", equipment: "dumbbell", primaryMuscle: "triceps", category: "push", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "12-15", restSeconds: 60, score: 76, movement: "isolation", isPrimary: false },
    { id: "push_014", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Barbell_Bench_Press/0.jpg", name: "Close Grip Bench Press", equipment: "barbell", primaryMuscle: "triceps", category: "push", location: ["gym"], difficulty: ["intermediate"], sets: 3, reps: "8-12", restSeconds: 90, score: 76, movement: "compound", isPrimary: true },
    { id: "push_015", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/EZ-Bar_Skullcrusher/0.jpg", name: "Skull Crushers", equipment: "barbell", primaryMuscle: "triceps", category: "push", location: ["gym"], difficulty: ["intermediate"], sets: 3, reps: "10-12", restSeconds: 60, score: 75, movement: "isolation", isPrimary: false },
    // PUSH - HOME
    { id: "push_h001", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pushups/0.jpg", name: "Push-Up", equipment: "bodyweight", primaryMuscle: "chest", category: "push", location: ["home"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "10-20", restSeconds: 60, score: 77, movement: "compound", isPrimary: true },
    { id: "push_h002", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Push-Up_Wide/0.jpg", name: "Wide Push-Up", equipment: "bodyweight", primaryMuscle: "chest", category: "push", location: ["home"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "10-20", restSeconds: 60, score: 61, movement: "compound", isPrimary: false },
    { id: "push_h003", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Push-Ups_-_Close_Triceps_Position/0.jpg", name: "Diamond Push-Up", equipment: "bodyweight", primaryMuscle: "triceps", category: "push", location: ["home"], difficulty: ["intermediate"], sets: 3, reps: "8-15", restSeconds: 60, score: 69, movement: "compound", isPrimary: false },
    { id: "push_h004", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Handstand_Push-Ups/0.jpg", name: "Pike Push-Up", equipment: "bodyweight", primaryMuscle: "shoulders", category: "push", location: ["home"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "8-15", restSeconds: 60, score: 67, movement: "compound", isPrimary: true },
    { id: "push_h005", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bench_Dips/0.jpg", name: "Tricep Dips", equipment: "bodyweight", primaryMuscle: "triceps", category: "push", location: ["home"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "10-15", restSeconds: 60, score: 73, movement: "compound", isPrimary: true },
    { id: "push_h006", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Push-Up/0.jpg", name: "Decline Push-Up", equipment: "bodyweight", primaryMuscle: "chest", category: "push", location: ["home"], difficulty: ["intermediate"], sets: 3, reps: "10-15", restSeconds: 60, score: 65, movement: "compound", isPrimary: false },
    // PULL - GYM
    { id: "pull_001", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Barbell_Row/0.jpg", name: "Barbell Row", equipment: "barbell", primaryMuscle: "back", category: "pull", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 4, reps: "8-12", restSeconds: 90, score: 90, movement: "compound", isPrimary: true },
    { id: "pull_002", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Dumbbell_Row/0.jpg", name: "Dumbbell Row", equipment: "dumbbell", primaryMuscle: "back", category: "pull", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "10-12", restSeconds: 90, score: 85, movement: "compound", isPrimary: false },
    { id: "pull_003", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Lat_Pulldown/0.jpg", name: "Lat Pulldown", equipment: "cable", primaryMuscle: "back", category: "pull", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 4, reps: "10-12", restSeconds: 90, score: 87, movement: "compound", isPrimary: false },
    { id: "pull_004", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Cable_Rows/0.jpg", name: "Cable Row", equipment: "cable", primaryMuscle: "back", category: "pull", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "10-12", restSeconds: 90, score: 85, movement: "compound", isPrimary: false },
    { id: "pull_005", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Face_Pull/0.jpg", name: "Face Pull", equipment: "cable", primaryMuscle: "rear delts", category: "pull", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "12-15", restSeconds: 60, score: 85, movement: "isolation", isPrimary: true },
    { id: "pull_006", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Reverse_Flyes/0.jpg", name: "Reverse Fly", equipment: "dumbbell", primaryMuscle: "rear delts", category: "pull", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "12-15", restSeconds: 60, score: 79, movement: "isolation", isPrimary: false },
    { id: "pull_007", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curl/0.jpg", name: "Barbell Curl", equipment: "barbell", primaryMuscle: "biceps", category: "pull", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "10-12", restSeconds: 60, score: 86, movement: "isolation", isPrimary: true },
    { id: "pull_008", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bicep_Curl/0.jpg", name: "Dumbbell Curl", equipment: "dumbbell", primaryMuscle: "biceps", category: "pull", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "10-12", restSeconds: 60, score: 85, movement: "isolation", isPrimary: false },
    { id: "pull_009", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hammer_Curls/0.jpg", name: "Hammer Curl", equipment: "dumbbell", primaryMuscle: "biceps", category: "pull", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "10-12", restSeconds: 60, score: 83, movement: "isolation", isPrimary: false },
    { id: "pull_010", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Preacher_Curl/0.jpg", name: "Preacher Curl", equipment: "barbell", primaryMuscle: "biceps", category: "pull", location: ["gym"], difficulty: ["intermediate"], sets: 3, reps: "10-12", restSeconds: 60, score: 78, movement: "isolation", isPrimary: false },
    { id: "pull_011", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Deadlift/0.jpg", name: "Deadlift", equipment: "barbell", primaryMuscle: "back", category: "pull", location: ["gym"], difficulty: ["intermediate"], sets: 4, reps: "5-8", restSeconds: 120, score: 89, movement: "compound", isPrimary: false },
    // PULL - HOME
    { id: "pull_h001", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pullups/0.jpg", name: "Pull-Up", equipment: "bodyweight", primaryMuscle: "back", category: "pull", location: ["home"], difficulty: ["intermediate"], sets: 4, reps: "5-10", restSeconds: 90, score: 88, movement: "compound", isPrimary: true },
    { id: "pull_h002", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Chin-Up/0.jpg", name: "Chin-Up", equipment: "bodyweight", primaryMuscle: "biceps", category: "pull", location: ["home"], difficulty: ["intermediate"], sets: 3, reps: "5-10", restSeconds: 90, score: 86, movement: "compound", isPrimary: true },
    { id: "pull_h003", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Inverted_Row/0.jpg", name: "Inverted Row", equipment: "bodyweight", primaryMuscle: "back", category: "pull", location: ["home"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "10-15", restSeconds: 60, score: 74, movement: "compound", isPrimary: true },
    // LEGS - GYM
    { id: "legs_001", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat/0.jpg", name: "Barbell Squat", equipment: "barbell", primaryMuscle: "quads", category: "legs", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 4, reps: "8-12", restSeconds: 120, score: 93, movement: "compound", isPrimary: true },
    { id: "legs_002", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/0.jpg", name: "Leg Press", equipment: "machine", primaryMuscle: "quads", category: "legs", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 4, reps: "10-12", restSeconds: 90, score: 86, movement: "compound", isPrimary: false },
    { id: "legs_003", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hack_Squat/0.jpg", name: "Hack Squat", equipment: "machine", primaryMuscle: "quads", category: "legs", location: ["gym"], difficulty: ["intermediate"], sets: 3, reps: "10-12", restSeconds: 90, score: 83, movement: "compound", isPrimary: false },
    { id: "legs_004", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lunges/0.jpg", name: "Dumbbell Lunges", equipment: "dumbbell", primaryMuscle: "quads", category: "legs", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "10-12", restSeconds: 60, score: 81, movement: "compound", isPrimary: false },
    { id: "legs_005", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/0.jpg", name: "Romanian Deadlift", equipment: "barbell", primaryMuscle: "hamstrings", category: "legs", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 4, reps: "8-12", restSeconds: 90, score: 89, movement: "compound", isPrimary: true },
    { id: "legs_006", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Leg_Curls/0.jpg", name: "Leg Curl", equipment: "machine", primaryMuscle: "hamstrings", category: "legs", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "12-15", restSeconds: 60, score: 87, movement: "isolation", isPrimary: false },
    { id: "legs_007", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Stiff-Legged_Dumbbell_Deadlift/0.jpg", name: "Dumbbell RDL", equipment: "dumbbell", primaryMuscle: "hamstrings", category: "legs", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "10-12", restSeconds: 90, score: 79, movement: "compound", isPrimary: false },
    { id: "legs_008", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hip_Thrust/0.jpg", name: "Hip Thrust", equipment: "barbell", primaryMuscle: "glutes", category: "legs", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 4, reps: "10-12", restSeconds: 90, score: 89, movement: "compound", isPrimary: true },
    { id: "legs_009", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Calf_Raise/0.jpg", name: "Seated Calf Raise", equipment: "machine", primaryMuscle: "calves", category: "legs", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 4, reps: "12-15", restSeconds: 60, score: 83, movement: "isolation", isPrimary: false },
    { id: "legs_010", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises/0.jpg", name: "Standing Calf Raise", equipment: "machine", primaryMuscle: "calves", category: "legs", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 4, reps: "12-15", restSeconds: 60, score: 86, movement: "isolation", isPrimary: true },
    { id: "legs_011", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Goblet_Squat/0.jpg", name: "Goblet Squat", equipment: "dumbbell", primaryMuscle: "quads", category: "legs", location: ["gym"], difficulty: ["beginner"], sets: 3, reps: "12-15", restSeconds: 60, score: 75, movement: "compound", isPrimary: false },
    { id: "legs_012", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Extensions/0.jpg", name: "Leg Extension", equipment: "machine", primaryMuscle: "quads", category: "legs", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "12-15", restSeconds: 60, score: 81, movement: "isolation", isPrimary: false },
    // LEGS - HOME
    { id: "legs_h001", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bodyweight_Squat/0.jpg", name: "Bodyweight Squat", equipment: "bodyweight", primaryMuscle: "quads", category: "legs", location: ["home"], difficulty: ["beginner"], sets: 3, reps: "15-20", restSeconds: 60, score: 63, movement: "compound", isPrimary: false },
    { id: "legs_h002", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Freehand_Jump_Squat/0.jpg", name: "Jump Squat", equipment: "bodyweight", primaryMuscle: "quads", category: "legs", location: ["home"], difficulty: ["intermediate"], sets: 3, reps: "10-15", restSeconds: 60, score: 60, movement: "compound", isPrimary: false },
    { id: "legs_h003", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bodyweight_Walking_Lunge/0.jpg", name: "Walking Lunges", equipment: "bodyweight", primaryMuscle: "quads", category: "legs", location: ["home"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "12-15", restSeconds: 60, score: 78, movement: "compound", isPrimary: false },
    { id: "legs_h004", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Split_Squats/0.jpg", name: "Bulgarian Split Squat", equipment: "bodyweight", primaryMuscle: "quads", category: "legs", location: ["home"], difficulty: ["intermediate"], sets: 3, reps: "10-12", restSeconds: 60, score: 82, movement: "compound", isPrimary: true },
    { id: "legs_h005", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Glute_Bridge/0.jpg", name: "Glute Bridge", equipment: "bodyweight", primaryMuscle: "glutes", category: "legs", location: ["home"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "15-20", restSeconds: 60, score: 74, movement: "compound", isPrimary: true },
    { id: "legs_h006", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Single_Leg_Glute_Bridge/0.jpg", name: "Single Leg Glute Bridge", equipment: "bodyweight", primaryMuscle: "glutes", category: "legs", location: ["home"], difficulty: ["intermediate"], sets: 3, reps: "12-15", restSeconds: 60, score: 70, movement: "compound", isPrimary: false },
    { id: "legs_h007", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Natural_Glute_Ham_Raise/0.jpg", name: "Nordic Curl", equipment: "bodyweight", primaryMuscle: "hamstrings", category: "legs", location: ["home"], difficulty: ["intermediate"], sets: 3, reps: "6-10", restSeconds: 90, score: 77, movement: "isolation", isPrimary: true },
    { id: "legs_h008", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Calf_Raises/0.jpg", name: "Calf Raise", equipment: "bodyweight", primaryMuscle: "calves", category: "legs", location: ["home"], difficulty: ["beginner", "intermediate"], sets: 4, reps: "20-25", restSeconds: 45, score: 64, movement: "isolation", isPrimary: true },
    { id: "legs_h009", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Step-up_with_Knee_Raise/0.jpg", name: "Step-Up", equipment: "bodyweight", primaryMuscle: "quads", category: "legs", location: ["home"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "12-15", restSeconds: 60, score: 70, movement: "compound", isPrimary: false },
    // CHEST GYM
    { id: "push_016", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent-Arm_Dumbbell_Pullover/0.jpg", name: "Dumbbell Pullover", equipment: "dumbbell", primaryMuscle: "chest", category: "push", location: ["gym"], difficulty: ["intermediate"], sets: 3, reps: "12-15", restSeconds: 60, score: 59, movement: "isolation", isPrimary: false },
    { id: "push_017", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Dumbbell_Bench_Press/0.jpg", name: "Decline Dumbbell Press", equipment: "dumbbell", primaryMuscle: "chest", category: "push", location: ["gym"], difficulty: ["intermediate"], sets: 3, reps: "10-12", restSeconds: 90, score: 69, movement: "compound", isPrimary: false },
    { id: "push_018", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Barbell_Bench_Press/0.jpg", name: "Decline Barbell Press", equipment: "barbell", primaryMuscle: "chest", category: "push", location: ["gym"], difficulty: ["intermediate"], sets: 3, reps: "8-12", restSeconds: 90, score: 71, movement: "compound", isPrimary: false },
    { id: "push_019", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover/0.jpg", name: "High Cable Fly", equipment: "cable", primaryMuscle: "chest", category: "push", location: ["gym"], difficulty: ["intermediate"], sets: 3, reps: "12-15", restSeconds: 60, score: 73, movement: "isolation", isPrimary: false },
    { id: "push_020", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dips_-_Chest_Version/0.jpg", name: "Chest Dips", equipment: "bodyweight", primaryMuscle: "chest", category: "push", location: ["gym"], difficulty: ["intermediate"], sets: 3, reps: "8-12", restSeconds: 90, score: 79, movement: "compound", isPrimary: false },
    { id: "push_021", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Bench_Press_-_Medium_Grip/0.jpg", name: "Paused Bench Press", equipment: "barbell", primaryMuscle: "chest", category: "push", location: ["gym"], difficulty: ["intermediate"], sets: 4, reps: "5-8", restSeconds: 120, score: 63, movement: "compound", isPrimary: false },
    // SHOULDERS GYM
    { id: "push_022", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Barbell_Military_Press/0.jpg", name: "Seated Barbell Press", equipment: "barbell", primaryMuscle: "shoulders", category: "push", location: ["gym"], difficulty: ["intermediate"], sets: 4, reps: "6-10", restSeconds: 120, score: 81, movement: "compound", isPrimary: false },
    { id: "push_023", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Seated_Lateral_Raise/0.jpg", name: "Cable Lateral Raise", equipment: "cable", primaryMuscle: "shoulders", category: "push", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "12-15", restSeconds: 60, score: 87, movement: "isolation", isPrimary: false },
    { id: "push_024", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Upright_Barbell_Row/0.jpg", name: "Upright Row", equipment: "barbell", primaryMuscle: "shoulders", category: "push", location: ["gym"], difficulty: ["intermediate"], sets: 3, reps: "10-12", restSeconds: 60, score: 60, movement: "compound", isPrimary: false },
    { id: "push_025", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Dumbbell_Press/0.jpg", name: "Seated Dumbbell Press", equipment: "dumbbell", primaryMuscle: "shoulders", category: "push", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 4, reps: "8-12", restSeconds: 90, score: 85, movement: "compound", isPrimary: false },
    { id: "push_026", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Machine_Shoulder_Military_Press/0.jpg", name: "Machine Shoulder Press", equipment: "machine", primaryMuscle: "shoulders", category: "push", location: ["gym"], difficulty: ["beginner"], sets: 3, reps: "10-12", restSeconds: 90, score: 71, movement: "compound", isPrimary: false },
    // TRICEPS GYM
    { id: "push_027", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Rope_Overhead_Triceps_Extension/0.jpg", name: "Cable Overhead Tricep Extension", equipment: "cable", primaryMuscle: "triceps", category: "push", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "12-15", restSeconds: 60, score: 81, movement: "isolation", isPrimary: false },
    { id: "push_028", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/EZ-Bar_Skullcrusher/0.jpg", name: "EZ Bar Skull Crusher", equipment: "barbell", primaryMuscle: "triceps", category: "push", location: ["gym"], difficulty: ["intermediate"], sets: 3, reps: "10-12", restSeconds: 60, score: 77, movement: "isolation", isPrimary: false },
    { id: "push_029", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Tricep_Dumbbell_Kickback/0.jpg", name: "Tricep Kickback", equipment: "dumbbell", primaryMuscle: "triceps", category: "push", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "12-15", restSeconds: 60, score: 59, movement: "isolation", isPrimary: false },
    { id: "push_030", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dips_-_Triceps_Version/0.jpg", name: "Tricep Dips", equipment: "bodyweight", primaryMuscle: "triceps", category: "push", location: ["gym"], difficulty: ["intermediate"], sets: 3, reps: "8-12", restSeconds: 90, score: 76, movement: "compound", isPrimary: false },
    { id: "push_031", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Board_Press/0.jpg", name: "Board Press", equipment: "barbell", primaryMuscle: "triceps", category: "push", location: ["gym"], difficulty: ["intermediate"], sets: 3, reps: "6-10", restSeconds: 90, score: 52, movement: "compound", isPrimary: false },
    // BACK GYM
    { id: "pull_012", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Front_Lat_Pulldown/0.jpg", name: "Close Grip Lat Pulldown", equipment: "cable", primaryMuscle: "back", category: "pull", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "10-12", restSeconds: 90, score: 78, movement: "compound", isPrimary: false },
    { id: "pull_013", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/T-Bar_Row_with_Handle/0.jpg", name: "T-Bar Row", equipment: "barbell", primaryMuscle: "back", category: "pull", location: ["gym"], difficulty: ["intermediate"], sets: 4, reps: "8-12", restSeconds: 90, score: 84, movement: "compound", isPrimary: false },
    { id: "pull_014", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Cable_Rows/0.jpg", name: "Wide Grip Cable Row", equipment: "cable", primaryMuscle: "back", category: "pull", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "10-12", restSeconds: 90, score: 77, movement: "compound", isPrimary: false },
    { id: "pull_015", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Rear_Pull-Up/0.jpg", name: "Wide Grip Pull-Up", equipment: "bodyweight", primaryMuscle: "back", category: "pull", location: ["gym"], difficulty: ["intermediate"], sets: 4, reps: "5-10", restSeconds: 90, score: 88, movement: "compound", isPrimary: true },
    { id: "pull_016", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hyperextensions_Back_Extensions/0.jpg", name: "Back Extension", equipment: "machine", primaryMuscle: "back", category: "pull", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "12-15", restSeconds: 60, score: 60, movement: "isolation", isPrimary: false },
    { id: "pull_017", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Two-Dumbbell_Row/0.jpg", name: "Chest Supported Row", equipment: "dumbbell", primaryMuscle: "back", category: "pull", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "10-12", restSeconds: 90, score: 80, movement: "compound", isPrimary: false },
    // REAR DELTS GYM
    { id: "pull_018", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench/0.jpg", name: "Bent Over Rear Delt Fly", equipment: "dumbbell", primaryMuscle: "rear delts", category: "pull", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "12-15", restSeconds: 60, score: 80, movement: "isolation", isPrimary: false },
    { id: "pull_019", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Face_Pull/0.jpg", name: "Cable Face Pull High", equipment: "cable", primaryMuscle: "rear delts", category: "pull", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "15-20", restSeconds: 45, score: 76, movement: "isolation", isPrimary: false },
    { id: "pull_020", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Rear_Delt_Row/0.jpg", name: "Rear Delt Barbell Row", equipment: "barbell", primaryMuscle: "rear delts", category: "pull", location: ["gym"], difficulty: ["intermediate"], sets: 3, reps: "12-15", restSeconds: 60, score: 57, movement: "compound", isPrimary: false },
    { id: "pull_021", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Bent-Over_Rear_Delt_Raise/0.jpg", name: "Seated Rear Delt Raise", equipment: "dumbbell", primaryMuscle: "rear delts", category: "pull", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "12-15", restSeconds: 60, score: 73, movement: "isolation", isPrimary: false },
    // BICEPS GYM
    { id: "pull_022", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/EZ-Bar_Curl/0.jpg", name: "EZ Bar Curl", equipment: "barbell", primaryMuscle: "biceps", category: "pull", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "10-12", restSeconds: 60, score: 84, movement: "isolation", isPrimary: false },
    { id: "pull_023", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Curl/0.jpg", name: "Incline Dumbbell Curl", equipment: "dumbbell", primaryMuscle: "biceps", category: "pull", location: ["gym"], difficulty: ["intermediate"], sets: 3, reps: "10-12", restSeconds: 60, score: 82, movement: "isolation", isPrimary: false },
    { id: "pull_024", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Biceps_Cable_Curl/0.jpg", name: "Cable Curl", equipment: "cable", primaryMuscle: "biceps", category: "pull", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "12-15", restSeconds: 60, score: 78, movement: "isolation", isPrimary: false },
    { id: "pull_025", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Concentration_Curls/0.jpg", name: "Concentration Curl", equipment: "dumbbell", primaryMuscle: "biceps", category: "pull", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "10-12", restSeconds: 60, score: 73, movement: "isolation", isPrimary: false },
    { id: "pull_026", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Zottman_Curl/0.jpg", name: "Zottman Curl", equipment: "dumbbell", primaryMuscle: "biceps", category: "pull", location: ["gym"], difficulty: ["intermediate"], sets: 3, reps: "10-12", restSeconds: 60, score: 60, movement: "isolation", isPrimary: false },
    // HOME PULL
    { id: "pull_h004", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/V-Bar_Pullup/0.jpg", name: "Neutral Grip Pull-Up", equipment: "bodyweight", primaryMuscle: "back", category: "pull", location: ["home"], difficulty: ["intermediate"], sets: 3, reps: "5-10", restSeconds: 90, score: 77, movement: "compound", isPrimary: false },
    { id: "pull_h005", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Inverted_Row/0.jpg", name: "Wide Inverted Row", equipment: "bodyweight", primaryMuscle: "back", category: "pull", location: ["home"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "10-15", restSeconds: 60, score: 71, movement: "compound", isPrimary: false },
    { id: "pull_h006", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Pullups/0.jpg", name: "Commando Pull-Up", equipment: "bodyweight", primaryMuscle: "back", category: "pull", location: ["home"], difficulty: ["intermediate"], sets: 3, reps: "5-8", restSeconds: 90, score: 57, movement: "compound", isPrimary: false },
    { id: "pull_h007", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Alternate_Hammer_Curl/0.jpg", name: "Towel Bicep Curl", equipment: "bodyweight", primaryMuscle: "biceps", category: "pull", location: ["home"], difficulty: ["beginner"], sets: 3, reps: "10-15", restSeconds: 60, score: 51, movement: "isolation", isPrimary: false },
    // ABS GYM
    { id: "abs_001", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crunch/0.jpg", name: "Cable Crunch", equipment: "cable", primaryMuscle: "abs", category: "core", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "12-15", restSeconds: 60, score: 85, movement: "isolation", isPrimary: true },
    { id: "abs_002", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/0.jpg", name: "Hanging Leg Raise", equipment: "bodyweight", primaryMuscle: "abs", category: "core", location: ["gym"], difficulty: ["intermediate"], sets: 3, reps: "10-15", restSeconds: 60, score: 85, movement: "isolation", isPrimary: false },
    { id: "abs_003", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Ab_Crunch_Machine/0.jpg", name: "Ab Machine Crunch", equipment: "machine", primaryMuscle: "abs", category: "core", location: ["gym"], difficulty: ["beginner"], sets: 3, reps: "15-20", restSeconds: 45, score: 75, movement: "isolation", isPrimary: false },
    { id: "abs_004", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Crunch/0.jpg", name: "Decline Crunch", equipment: "bodyweight", primaryMuscle: "abs", category: "core", location: ["gym"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "15-20", restSeconds: 45, score: 74, movement: "isolation", isPrimary: false },
    { id: "abs_005", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Oblique_Crunches/0.jpg", name: "Oblique Crunch", equipment: "bodyweight", primaryMuscle: "abs", category: "core", location: ["gym"], difficulty: ["beginner"], sets: 3, reps: "15-20", restSeconds: 45, score: 62, movement: "isolation", isPrimary: false },
    { id: "abs_006", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Landmine_180s/0.jpg", name: "Landmine Rotation", equipment: "barbell", primaryMuscle: "abs", category: "core", location: ["gym"], difficulty: ["intermediate"], sets: 3, reps: "12-15", restSeconds: 60, score: 57, movement: "isolation", isPrimary: false },
    // ABS HOME
    { id: "abs_h001", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Crunch_-_Hands_Overhead/0.jpg", name: "Crunch", equipment: "bodyweight", primaryMuscle: "abs", category: "core", location: ["home"], difficulty: ["beginner"], sets: 3, reps: "20-25", restSeconds: 45, score: 71, movement: "isolation", isPrimary: false },
    { id: "abs_h002", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/0.jpg", name: "Plank", equipment: "bodyweight", primaryMuscle: "abs", category: "core", location: ["home"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "30-60s", restSeconds: 45, score: 70, movement: "isolation", isPrimary: false },
    { id: "abs_h003", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Flat_Bench_Lying_Leg_Raise/0.jpg", name: "Leg Raise", equipment: "bodyweight", primaryMuscle: "abs", category: "core", location: ["home"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "12-15", restSeconds: 45, score: 78, movement: "isolation", isPrimary: true },
    { id: "abs_h004", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Air_Bike/0.jpg", name: "Bicycle Crunch", equipment: "bodyweight", primaryMuscle: "abs", category: "core", location: ["home"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "20-25", restSeconds: 45, score: 78, movement: "isolation", isPrimary: false },
    { id: "abs_h005", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Mountain_Climbers/0.jpg", name: "Mountain Climbers", equipment: "bodyweight", primaryMuscle: "abs", category: "core", location: ["home"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "20-30", restSeconds: 45, score: 59, movement: "isolation", isPrimary: false },
    { id: "abs_h006", imageUrl: "https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Russian_Twist/0.jpg", name: "Russian Twist", equipment: "bodyweight", primaryMuscle: "abs", category: "core", location: ["home"], difficulty: ["beginner", "intermediate"], sets: 3, reps: "20-25", restSeconds: 45, score: 63, movement: "isolation", isPrimary: false },
];